### ISSUE TITLE
debugging checklist for v13.5

### ISSUE THREAD

**Issue by steveseguin** [steveseguin/vdo.ninja#565]
- [ ] switching audio input source on guestA made the guestA tile go grey for guestB 
- [ ] submit error log: bug icon is not clickable
- [ ] &device=0 is borked ; video still shows and text is wrong. **[I'm not able to reproduce]**
- [ ] audio reconnection logic on device unplug/plugin is strange
- [ ] permissions error with two tabs open?

Optional for release
- [ ] advanced settings buttons for a/v should be toggles
- [ ] agc/ec/noise: guest tile in control center flickers when toggled **[can't fix - chrome issue]**
- [ ] UI doesn't make it clear which directions the agc/ec/ns toggles work
- [x] latency in advanced audio settings looks like a slider
- [ ] 'close settings' button would make more sense at the bottom of the dialog
- [ ] Audio Sources UI in guest settings is still broken   ( I simply can't figure out what's causing it  )
- [ ] pop-out chat button and pop-up size/position needs work. 
- [ ] prevent pop-out chat from working on mobile
- [ ] If preview is stopped, message that it is stopped

re: session timer being visible.  The current session timer is just a hacked in solution for the time being. I'll work a proper timer in once I get the audio-visualizer meter added also. The CSS to make this always visible and correctly positioned is challenging for me.

re: "sending stats window: doesn't reset anymore, but flickers every now and then"  -- as in it's broken or that it just flickers?

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/101021311-c50a5d00-353d-11eb-9340-0ce1b299e3c8.png)
&device=0 works as expect for me?
